--
-- This scripts creates the wrapper and other SQL objects required to test the 
--   code on the local DB2 instance running in Docker
-- It assumes that the local Fabric test app is also running and set up WITH TLS
--

-- Registering the Wrapper

CREATE WRAPPER fabric LIBRARY 'libdb2qgjava.so'
OPTIONS (

    -- Our Wrapper class

    UNFENCED_WRAPPER_CLASS      'com.ibm.federation.fabric.unfenced.FabricUnfencedWrapper',

    -- A KMS Connector to retrieve the crypto artefacts used to access the ledger
    --
    -- It can be one of our current KMS Connector implementations:
    -- 1) CRYPTOGEN_FS_KMS  - A KMS using the file structure generated by the Fabric cryptogen tool on the instance local file system
    -- 2) COMPOSER_FS_KMS   - A KMS using a Hyperledger Composer business card stored on the instance local file system
    -- 3) CUSTOM_FS_KMS     - A KMS allowing to pass explicit cert & key files stored on the instance local file system
    -- 4) NODE_KVS_FS_KMS   - A KMS using the file structure generated by the Node.js SDK fileSystem KVS on the instance local file system

    KMS_CONNECTOR               'CRYPTOGEN_FS_KMS'
);

-- Creating the Server
--   (representing a peer on the Blockchain network we're connecting to)

CREATE SERVER org1_peer0 WRAPPER fabric
OPTIONS (

    -- The details of the Hyperledger Fabric peer we are connecting to

    PEER_URL                    'grpcs://peer0.org1.example.com:7051',
    PEER_TLS_CA_CERT_FILE       '/fabric/app/network/config/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt',
    PEER_TLS_HOSTNAME_OVERRIDE  'peer0.org1.example.com',

    -- The parameters for the KMS Connector chosen when creating the Wrapper

    KMS_FS_MSP_ID               'Org1MSP',
    KMS_FS_CRYPTOGEN_ORG_ROOT   '/fabric/app/network/config/crypto-config/peerOrganizations/org1.example.com'
);

-- Create the User Mapping to specify which credentials will be used to access the blokchain

CREATE USER MAPPING FOR USER SERVER org1_peer0
OPTIONS (
    REMOTE_AUTHID               'User1'
);

-- Create the Nicknames to access the Blocks & Transactions as local tables

CREATE NICKNAME nn_blocks FOR org1_peer0.twoorgchannel.blocks;
CREATE NICKNAME nn_blocks_opt FOR org1_peer0.twoorgchannel.blocks;
CREATE NICKNAME nn_tx FOR org1_peer0.twoorgchannel.transactions;
CREATE NICKNAME nn_tx_opt FOR org1_peer0.twoorgchannel.transactions;
